### ISSUE TITLE
Support in rtl? 

### ISSUE THREAD

**Issue by yossimal95** [firflant/react-form-component#22]
Hi,

There is any support in right to left?
(or maybe a way to insert costume css in order to do so..?) 

Tanks!

**Comment by yossimal95** [comment]
I've been manage to solve it using the form's class name attribute.
I added my own class and changed the style of the default class via my new class.

Tanks anyway..!

**Comment by firflant** [comment]
@yossimal95 Can you give the example? Development of `react-form-component` package has been reinitiated this month and i may consider adding new functions.

**Comment by yossimal95** [comment]
Hi,
Sure :-)

I added this CSS:
```.rtl {
  direction: rtl;
}

.rtl input {
  direction: rtl;
  text-align: right;
}

.rtl label {
  direction: rtl;
  text-align: right;
}
```
Then, I added this JSX
```
const BasicExampleForm = ({ rtl }) => // rtl param..
  <Form fields={['name', 'email', 'type']} className={rtl && 'rtl'}> {/* using the rtl param */}
    <Input
      name='name'
      label='שלום?'
    />
    <Input
      name='email'
      type='email'
      label='E-mail'
    />
    <FormButton
      onClick={fields => console.log(fields)}
    >Save</FormButton>
  </Form>
```
Basically, it's okay, but I still need an option to change the Help notice to Hebrew..


![image](https://github.com/user-attachments/assets/50136adb-0300-4990-94ec-2a4445c59bf0)

**Comment by firflant** [comment]
@yossimal95 RTL support added to  version `2.8.0`.  Activated by a dedicated theme typography setting:

```
<FormThemeProvider theme={{ typography: { direction: 'rtl' } }}>
```

**Comment by firflant** [comment]
For error text labels, see `textLabels` part of the customizable theme object
https://firflant.github.io/react-form-component/?path=/story/docs-theming--page

**Comment by yossimal95** [comment]
> @yossimal95 RTL support added to  version `2.8.0`.  Activated by a dedicated theme typography setting:
> 
> ```
> <FormThemeProvider theme={{ typography: { direction: 'rtl' } }}>
> ```

Cool!
Tnks..!
I'll check it out🙏👍
