### ISSUE TITLE
TypeError: Cannot read property 'sizes' of undefined theme node_modules/react-standalone-form/lib/core/FormThemeProvider.js:57

### ISSUE THREAD

**Issue by farhanapakkir** [firflant/react-form-component#5]
I tried "react-standalone-form" latest version "1.1.0"  in newly created react app using createReactapp following this article "https://blog.mvp-space.com/learn-the-simple-way-of-building-forms-in-react-using-context-api-2a6b9e908fdb". Its throwing the error 

**Uncaught TypeError: Cannot read property 'errorNotificationFunc' of undefined**

Then i tried other older versions from 0.2.0 to 0.9.4. Its working. 

When i tired 0.10.0 the issue starts. This version throws 

**TypeError: Cannot read property 'sizes' of undefined
theme
node_modules/react-standalone-form/lib/core/FormThemeProvider.js:57**

I have just copy pasted the code mentioned in the article. (The code is same as the sample code mentioned in the readMe of "react-standalone-form") Not changed any thing. 

Now im using version 0.9.4. It works fine. what should i do to use the latest versions?

Thanks in advance.

**Comment by farhanapakkir** [comment]
Solution Here https://stackoverflow.com/questions/62813084/the-react-standalone-form-is-not-working

**Comment by firflant** [comment]
It has been fixed in version 1.4.8.
